# .streamlit/secrets.toml
# Securely store your database credentials here.
# Streamlit will automatically load these into st.secrets

[mysql]
host = "localhost"
user = "root"
password = "RAM123@Nova"  # Replace with your actual MySQL password
